# The URL the site will be built for
base_url = "https://nyc-website.redham28.workers.dev/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feeds = true

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"
smart_punctuation = true
definition_list = true
bottom_footnotes = true

[extra]
turnstile_key = "0x4AAAAAAEFi_qR0j4UNXBCX"
brand_img = "nycrs.png"
facebook_link = "https://www.facebook.com/nycrevolutionarysocialists"
instagram_link="https://www.instagram.com/redsparknyc/"
instagram_handle="redsparknyc"
twitter_link="https://twitter.com/NYCsocialists"
group_name="NYC Revolutionary Socialists"
group_type="local"
group_shorthand="NYCRS"
group_blurb="started in 2026. We're working with other locals that stayed together and other socialist organizations around the country to build a new national organization, currently Red Spark communists."
contact_img="srssign.jpeg"
contact_img_alt="A protest sign bearing the text 'SRS REVOLUTIONARY SOCIALISTS', defiant fists and the sickle and hammer"
group_location="nyc"
meeting_location="We meet on Thursday evenings from 7:30-8:30 pm EST on Zoom (bit.ly/nycrszoomlink) and in person at Prospect Park East"
