name = "seattle-website"
main = "build/index.js"
compatibility_date = "2026-07-15"

[build]
command = "cargo install \"worker-build@^0.8\" && worker-build --release"

[dev]
ip = "0.0.0.0"
port = 1111
local_protocol = "http"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
GITHUB_APP_ID = "4521864"
GITHUB_INSTALLATION_ID = "152071081"
GITHUB_OWNER = "communistjesus"
GITHUB_REPO = "srsnewwebsite"
GITHUB_BASE_BRANCH = "main"
DISCORD_PUBLIC_KEY="c46a6ce0a48b39f1399a7f5754baeaa13dbc5a2a2f1feffa742dc0b958f702d4"
DISCORD_BOT_CHANNEL="1534368771047817358"

[observability]
enabled = true
head_sampling_rate = 1